use_frameworks!

platform :ios, '10.0'

target 'RyScheduleCourseOC_Example' do
  pod 'RyScheduleCourseOC', :path => '../'

  target 'RyScheduleCourseOC_Tests' do
    inherit! :search_paths

    
  end
end
