use_frameworks!
source 'https://github.com/RisingSSR/RisingCyxbsSepc.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'RyScheduleCourseOC_Example' do
  pod 'RyScheduleCourseOC', :path => '../'

  target 'RyScheduleCourseOC_Tests' do
    inherit! :search_paths

    
  end
end
